theme: jekyll-theme-dinky 
title: The Seasonal Soundscape Project
descrpition: - [Recordings](https://jackhalgh.github.io/The-Seasonal-Soundscape-Project/January)
- [Local history](https://jackhalgh.github.io/The-Seasonal-Soundscape-Project/History)
- [Wildlife](https://jackhalgh.github.io/The-Seasonal-Soundscape-Project/Wildlife)
- [People](https://jackhalgh.github.io/The-Seasonal-Soundscape-Project/People)
