theme: jekyll-theme-minimal
title: The Seasonal Soundscape Project 
logo: ![EsWojlSW8AEW9n1](https://user-images.githubusercontent.com/74665965/105917854-e2821180-602a-11eb-90ae-7ee3d057075e.png)
github:
  is_project_page: false
